name: Build LaTeX Documents

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_pdf:
    runs-on: ubuntu-24.04 # Noble
    if: contains(github.event.head_commit.message, '@build_doc') || github.event_name == 'workflow_dispatch'
    strategy:
      matrix:
        target:
          - name: project_plan
            build_cmd: latexmk
            build_args: -pdf -interaction=nonstopmode -synctex=1 -f
            build_workdir: ./project_plan
            build_file: COMP1110-D08-Project-Plan.tex
            out_file: COMP1110-D08-Project-Plan.pdf
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure MiKTeX repository key for APT
        run: |
          curl -fsSL https://miktex.org/download/key | gpg --dearmor | sudo tee /usr/share/keyrings/miktex-keyring.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/miktex-keyring.gpg] https://miktex.org/download/ubuntu noble universe" | sudo tee /etc/apt/sources.list.d/miktex.list
          sudo apt-get update

      - name: Install MiKTeX
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: miktex

      - name: Configure MiKTeX
        run: |
          miktexsetup finish
          initexmf --set-config-value [MPM]AutoInstall=1
          initexmf --enable-installer
          initexmf --update-fndb
          initexmf --mkmaps
          miktex packages update
          echo "PATH=$HOME/bin:$PATH" >> "$GITHUB_ENV"
          # temporary fix: some MiKTeX packages are not auto-installed, manually install:
          miktex packages install xkeyval || true
          miktex packages install kvsetkeys || true
          miktex packages install iftex || true
          miktex packages install kvoptions || true

      - name: Build LaTeX documents
        run: ${{ matrix.target.build_cmd }} ${{ matrix.target.build_args }} ${{ matrix.target.build_file }}
        working-directory: ${{ matrix.target.build_workdir }}

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target.name }}-pdf
          path: ${{ matrix.target.build_workdir }}/${{ matrix.target.out_file }}
          retention-days: 7
